services:
  mssql:
    image: ardonplay/lightest-mssql-pancake:latest
    container_name: "lightest-mssql-pancake"
    hostname: lightest-mssql-pancake
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: on-failure
    environment:
      SA_PASSWORD: "8lOhUL+55y8"
      ACCEPT_EULA: "Y"
      TZ: "Europe/Minsk"
      MSSQL_PID: Developer
    healthcheck:
      test: sqlcmd -U sa -P "$${SA_PASSWORD}" -C -Q "SELECT 1" -b -o /dev/null
      start_period: 10s
      timeout: 2s
      interval: 30s
      retries: 3
    volumes:
      - lightest-mssql-pancake-data:/var/opt/mssql
    ports:
      - 1433:1433
volumes:
  lightest-mssql-pancake-data:
    name: "lightest-mssql-pancake-data"

